// Code generated by protoc-gen-go. DO NOT EDIT.
// source: center/center.proto

package center

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// registe
type RegisterRequest struct {
	ServerName           string   `protobuf:"bytes,1,opt,name=serverName,proto3" json:"serverName,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Functions            []string `protobuf:"bytes,3,rep,name=functions,proto3" json:"functions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6400d989d59d2c95, []int{0}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

func (m *RegisterRequest) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *RegisterRequest) GetFunctions() []string {
	if m != nil {
		return m.Functions
	}
	return nil
}

type RegisterResponse struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6400d989d59d2c95, []int{1}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

// discovery
type DiscoveryRequest struct {
	Server               string   `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscoveryRequest) Reset()         { *m = DiscoveryRequest{} }
func (m *DiscoveryRequest) String() string { return proto.CompactTextString(m) }
func (*DiscoveryRequest) ProtoMessage()    {}
func (*DiscoveryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6400d989d59d2c95, []int{2}
}

func (m *DiscoveryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscoveryRequest.Unmarshal(m, b)
}
func (m *DiscoveryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscoveryRequest.Marshal(b, m, deterministic)
}
func (m *DiscoveryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscoveryRequest.Merge(m, src)
}
func (m *DiscoveryRequest) XXX_Size() int {
	return xxx_messageInfo_DiscoveryRequest.Size(m)
}
func (m *DiscoveryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscoveryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DiscoveryRequest proto.InternalMessageInfo

func (m *DiscoveryRequest) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

type DiscoveryResponse struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscoveryResponse) Reset()         { *m = DiscoveryResponse{} }
func (m *DiscoveryResponse) String() string { return proto.CompactTextString(m) }
func (*DiscoveryResponse) ProtoMessage()    {}
func (*DiscoveryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6400d989d59d2c95, []int{3}
}

func (m *DiscoveryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscoveryResponse.Unmarshal(m, b)
}
func (m *DiscoveryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscoveryResponse.Marshal(b, m, deterministic)
}
func (m *DiscoveryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscoveryResponse.Merge(m, src)
}
func (m *DiscoveryResponse) XXX_Size() int {
	return xxx_messageInfo_DiscoveryResponse.Size(m)
}
func (m *DiscoveryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscoveryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DiscoveryResponse proto.InternalMessageInfo

func (m *DiscoveryResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

// heat
type HeatRequest struct {
	SendTime             int64    `protobuf:"varint,1,opt,name=sendTime,proto3" json:"sendTime,omitempty"`
	ServerName           string   `protobuf:"bytes,2,opt,name=serverName,proto3" json:"serverName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeatRequest) Reset()         { *m = HeatRequest{} }
func (m *HeatRequest) String() string { return proto.CompactTextString(m) }
func (*HeatRequest) ProtoMessage()    {}
func (*HeatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6400d989d59d2c95, []int{4}
}

func (m *HeatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeatRequest.Unmarshal(m, b)
}
func (m *HeatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeatRequest.Marshal(b, m, deterministic)
}
func (m *HeatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeatRequest.Merge(m, src)
}
func (m *HeatRequest) XXX_Size() int {
	return xxx_messageInfo_HeatRequest.Size(m)
}
func (m *HeatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HeatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HeatRequest proto.InternalMessageInfo

func (m *HeatRequest) GetSendTime() int64 {
	if m != nil {
		return m.SendTime
	}
	return 0
}

func (m *HeatRequest) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

type HeatResponse struct {
	ResponseTime         int64    `protobuf:"varint,1,opt,name=responseTime,proto3" json:"responseTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeatResponse) Reset()         { *m = HeatResponse{} }
func (m *HeatResponse) String() string { return proto.CompactTextString(m) }
func (*HeatResponse) ProtoMessage()    {}
func (*HeatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6400d989d59d2c95, []int{5}
}

func (m *HeatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeatResponse.Unmarshal(m, b)
}
func (m *HeatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeatResponse.Marshal(b, m, deterministic)
}
func (m *HeatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeatResponse.Merge(m, src)
}
func (m *HeatResponse) XXX_Size() int {
	return xxx_messageInfo_HeatResponse.Size(m)
}
func (m *HeatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HeatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HeatResponse proto.InternalMessageInfo

func (m *HeatResponse) GetResponseTime() int64 {
	if m != nil {
		return m.ResponseTime
	}
	return 0
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "center.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "center.RegisterResponse")
	proto.RegisterType((*DiscoveryRequest)(nil), "center.DiscoveryRequest")
	proto.RegisterType((*DiscoveryResponse)(nil), "center.DiscoveryResponse")
	proto.RegisterType((*HeatRequest)(nil), "center.HeatRequest")
	proto.RegisterType((*HeatResponse)(nil), "center.HeatResponse")
}

func init() { proto.RegisterFile("center/center.proto", fileDescriptor_6400d989d59d2c95) }

var fileDescriptor_6400d989d59d2c95 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x50, 0xc1, 0x4a, 0x03, 0x31,
	0x14, 0xa4, 0x5d, 0x59, 0xba, 0x63, 0xc1, 0x35, 0x82, 0x2c, 0x22, 0x52, 0x82, 0x42, 0xf1, 0x50,
	0x41, 0xff, 0x40, 0x3c, 0xe8, 0xc5, 0x43, 0xf0, 0xe4, 0x6d, 0xcd, 0x3e, 0x25, 0x07, 0x93, 0xfa,
	0x5e, 0x5a, 0xf0, 0xef, 0xc5, 0x4d, 0x6a, 0xd7, 0x42, 0x4f, 0x99, 0x99, 0x3c, 0x66, 0xde, 0x3c,
	0x9c, 0x58, 0xf2, 0x91, 0xf8, 0x26, 0x3d, 0x8b, 0x25, 0x87, 0x18, 0x54, 0x99, 0x98, 0xb6, 0x38,
	0x32, 0xf4, 0xe1, 0x24, 0x12, 0x1b, 0xfa, 0x5a, 0x91, 0x44, 0x75, 0x01, 0x08, 0xf1, 0x9a, 0xf8,
	0xb9, 0xfd, 0xa4, 0x66, 0x34, 0x1b, 0xcd, 0x2b, 0x33, 0x50, 0x94, 0xc2, 0x41, 0xdb, 0x75, 0xdc,
	0x8c, 0xfb, 0x9f, 0x1e, 0xab, 0x73, 0x54, 0xef, 0x2b, 0x6f, 0xa3, 0x0b, 0x5e, 0x9a, 0x62, 0x56,
	0xcc, 0x2b, 0xb3, 0x15, 0xf4, 0x25, 0xea, 0x6d, 0x88, 0x2c, 0x83, 0x17, 0x52, 0x35, 0x0a, 0x62,
	0xce, 0xf6, 0xbf, 0x50, 0x5f, 0xa3, 0x7e, 0x70, 0x62, 0xc3, 0x9a, 0xf8, 0x7b, 0xb3, 0xcb, 0x29,
	0xca, 0x94, 0x9c, 0x07, 0x33, 0xd3, 0x57, 0x38, 0x1e, 0xcc, 0xee, 0xb5, 0x7c, 0xc2, 0xe1, 0x23,
	0xb5, 0x71, 0xe3, 0x76, 0x86, 0x89, 0x90, 0xef, 0x5e, 0x5c, 0xee, 0x55, 0x98, 0x3f, 0xbe, 0xd3,
	0x7a, 0xbc, 0xdb, 0x5a, 0xdf, 0x62, 0x9a, 0xac, 0x72, 0x98, 0xc6, 0x94, 0x33, 0x1e, 0xf8, 0xfd,
	0xd3, 0xee, 0xf1, 0x3a, 0x59, 0xe4, 0xb3, 0xbf, 0x95, 0xfd, 0xdd, 0xef, 0x7e, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x90, 0x2b, 0x55, 0x15, 0x8e, 0x01, 0x00, 0x00,
}
